# Generated by Django 4.0.6 on 2022-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='published',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='This field is filled automatically, you can leave this field blank', max_length=300, null=True, unique=True, verbose_name='Category slug'),
        ),
    ]
