# Generated by Django 4.0.6 on 2022-07-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required field', max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='This field is filled automatically, you can leave this field blank', max_length=300, null=True, unique=True, verbose_name='Post slug')),
                ('content', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(default='images/default.jpg', help_text='Featured image size: 1200X600 px', upload_to='images/blogs/', verbose_name='Featured image')),
                ('alt_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Image alternative text')),
                ('author', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('notify_users', models.BooleanField(default=False)),
                ('notify_users_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-created_at',),
            },
        ),
    ]
