# Generated by Django 4.0.6 on 2022-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', help_text='Featured image size: 1200X600 px', upload_to='static/images/blogs/', verbose_name='Featured image'),
        ),
    ]
